# Generated by Django 5.1.2 on 2024-11-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbrands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.URLField(null=True),
        ),
    ]
