# Generated by Django 5.1.2 on 2024-11-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbrands', '0002_remove_product_sku_product_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='url',
        ),
    ]
