# Generated by Django 5.1.2 on 2024-11-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonbrands', '0003_remove_brand_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
